import { S } from '../palette.js';

// ============================================================
//  BOSSES — Act I
// ============================================================
export const SP_BOSS_RATKING = S(`
................
.......KK.......
......KLWK......
.....KKWLKK.....
......KbBK......
.....KbBBbK.....
....KbBZZBbK....
....KbBnnBbK....
...KBBnBBnBBK...
..KBbnBBBBnbBK..
..KBBBBnnBBBBK..
..KKBBBBBBBBKK..
....KBBBBBBK....
.....KBBBBKKKK..
......KKKBBBBK..
.........KKKKK..
`);

export const SP_BOSS_WARLORD = S(`
................
....KK4444KK....
....K4LLLL4K....
...K4LLHHLL4K...
...KHGGHHGGHK...
...KHGZjjZGHK...
...KHGGjjGGHK...
....KHGGGGHK....
...KKnHGGHnKK...
..K54nGjjGn45K..
..K5n4GHHG4n5K..
..K5nGGHHGGn5K..
...KKHGGGGHKK...
....KG....GK....
....KG....GK....
...KKK....KKK...
`);

export const SP_BOSS_WIDOW = S(`
................
.......KK.......
.....KKuuKK.....
....KupPPpuK....
....KupZZpuK....
....KuPp1pPuK...
....KuPPpPPuK...
...KKuPpppPuKK..
..KupKuPPuKpuK..
..KuKKpPPpKKuK..
..KuKKpuupKKuK..
...KKKpPPpKKK...
.....KpPPpK.....
....KupPPpuK....
...KKK....KKK...
................
`);

export const SP_BOSS_DRAGON = S(`
.....KK.....KK..
....KrrK...KrrK.
....Kr1rKKKr1rK.
...KrR1RRRRR1rK.
...KrRRxxxxRRrK.
..KrRxRZZZZRxRrK
..KrRxRRRRRRxRrK
..KrRxRRrrRRxRrK
...KrRxRrrRxRrK.
....KrRxxxxRrK..
...KrRRxxxxRRrK.
...KrRRrRRrRRrK.
..KrRRrR..RrRRrK
..KKrRrK..KrRrKK
...KKrK....KrKK.
....KK......KK..
`);

// ===== 16 additional boss sprites (Claude Design) =====
export const SP_BOSS_OGRE = S(`
................
.....KKKKKK.....
....KbeeeebK....
....KeeZeZeK....
....KebnnbeK....
....KeeebeeK....
...KKeeeeeeKK...
..KbeeeeeeeebK..
..KbeeebbeeebK..
..KbeebbbbeebK..
...KbeeeeeebK...
...KKbbeebbKK...
....KKK..KKK....
....Kn....nK....
...KK......KK...
................
`);

// #5 — Grimfang, Alpha of Wolves  (slate-grey wolf)
export const SP_BOSS_WOLF = S(`
................
....K4K..K4K....
....K434K34K....
...K4334434K....
...K433ZZ334K...
...K4334Z334K...
...K4334n334K...
...K43ZZZZ34K...
....K4334334K...
...K4334K4334K..
..K43334K4334K..
..K43333K3334K..
..K43K333K3K4K..
..KK.KK..KK.KK..
................
................
`);

// #6 — The Hollow Knight  (pale-blue spectral plate)
export const SP_BOSS_HOLLOW = S(`
................
.....KKKKK......
....KCiiiCK.....
....KCZcZCK.....
....KCcCCcCK....
.....KCccCK.....
.....KCCCCK.....
....KCiiiiCK....
...KCiiCCiiCK...
...KCiCiiCiCK...
...KCiCiiCiCK...
....KCiiiiCK....
....KCKiiKCK....
.....KKCCKK.....
......KKKK......
......K..K......
`);

// #7 — Emberlich  (skull crowned in flame)
export const SP_BOSS_EMBERLICH = S(`
................
.......q........
......qQq.......
.....qQ1Qq......
....KKQ1QKK.....
...KOOQ1QOOK....
...KOZOOZOK.....
...KOOOnnOOK....
...KOZOZOZOK....
....KOOOOOK.....
...KqOOOOOqK....
..KqqOQQQQOqqK..
..KqQOOOOOOQqK..
...KqOK..KOqK...
....KK....KK....
................
`);

// #8 — The Maw  (red gullet, all teeth)
export const SP_BOSS_MAW = S(`
................
................
....KKKKKKKK....
...KRRRRRRRRK...
..KRRxxxxxxRRK..
..KRZRZRZRZRRK..
.KRRRRRRRRRRRRK.
.KRRRRRRRRRRRRK.
.KRRR9999LLRRK..
.KRRR9LLLLRRRK..
..KRRR9999RRRK..
..KRRZRZRZRZRK..
..KRRxxxxxxRRK..
...KRRRRRRRRK...
....KKKKKKKK....
................
`);

// #9 — Stoneheart Golem  (stone block, glowing red core)
export const SP_BOSS_GOLEM = S(`
................
....KKKKKKKK....
...K33333333K...
...K34344434K...
...K34454443K...
...K35Z44Z53K...
...K344444443K..
...K344xx4443K..
...K33xRRx333K..
..KKK3xRRx3KKK..
..K333xRRx333K..
..K33334x3333K..
..K3K33333333K..
..KKK......KKK..
..K33......33K..
................
`);

// #10 — Sythiss, Venomlord  (coiled green serpent)
export const SP_BOSS_SYTHISS = S(`
................
.......KK.......
......KGGK......
.....KGHHGK.....
....KGHZHZHGK...
....KGHHHHHGK...
....KGHHGGHHK...
.....KGZZGGK....
......KGGGK.....
.......KGK......
......KGGGK.....
.....KGHHHGK....
....KGHHHHHGK...
...KGHHGGHHGK...
....KGHHHHHGK...
.....KKGGKK.....
`);

// #11 — Wraith of the Deep  (translucent floating spectre)
export const SP_BOSS_WRAITH = S(`
................
......KKKK......
.....KiiiiK.....
....KiIIIIiK....
....KicIIcIK....
....KiIIIIIiK...
....KiIIIIIiK...
...KiIIIIIIIiK..
...KiIIcIcIIiK..
...KiIIIIIIIK...
...KiIIIIIIK....
...KiIIIIIK.....
...KiIIIIK......
...KKiIIK.......
....KiIK........
.....KK.........
`);

// #12 — Skarn the Executioner  (hooded headsman + axe)
export const SP_BOSS_SKARN = S(`
................
....KKKKKKK.....
...KRrrrrrrK....
...KrZRRRRZrK...
...KrRkkkkkRrK..
...KrRRRRRRRrK..
....KrRRRRRrK...
.....KKRRKK.K5K.
....KKRRRRKKK5K.
...KRrRRRRrRK5..
...KrRRRRRRrK6..
...KKRRRRRRKK6..
....KrK..KrK6...
....KK....KK6...
.............6..
.............6..
`);

// #13 — The Devourer  (purple maw + tentacles)
export const SP_BOSS_DEVOURER = S(`
................
.....KKKKKK.....
....KPuuuuPK....
...KPuZUUZuPK...
...KPuuPPuuPK...
...KPPuuuuPPK...
..KPPuuuuuPPK...
..KPPuuuuuuPK...
..KPuuuuuuuPK...
..KKPuuuuuPKK...
..KPKPuuuPKPK...
..KPK.KPK.KPK...
..KPK..K..KPK...
..KPK.....KPK...
..KKK.....KKK...
................
`);

// #14 — Frostbite Revenant  (icy undead, hanging icicles)
export const SP_BOSS_FROST = S(`
................
....KKKKKKKK....
...KciiiiicK....
...Kc5ccZcc5K...
...Kcicc5ccK....
...KciCCCCciK...
....KciCCciK....
....KKciciKK....
..KKKciicciKKK..
..Ki5KciiciK5i..
..KIIKciiciKII..
..KIIKKciiKKII..
..K5K.KciK.K5K..
..KK..KKKK..KK..
......K..K......
......K..K......
`);

// #15 — Infernal Brute  (horned orange demon)
export const SP_BOSS_BRUTE = S(`
................
...K..KKKK..K...
..KK.KOOOOK.KK..
...K.KOOOOK..K..
....KOO11OOK....
....KO1ZZ1OK....
....KO1OOOOK....
....KOOoooOK....
...KKOOOOOOKK...
..KOOOOOOOOOOK..
..KOOOqOOqOOOK..
..KKOOqOOqOOKK..
...KOK....KOK...
...KOK....KOK...
...KKK....KKK...
................
`);

// #16 — The Faceless  (hollow-faced robed thing)
export const SP_BOSS_FACELESS = S(`
................
......KKKK......
.....KK4KK4K....
....K434443K....
...K43333333K...
...K43kkkkk3K...
...K43kkkkk3K...
...K43kkkkk3K...
...K433333334K..
..K4333kk3333K..
..K4333kk3333K..
..K4333333333K..
..K4K33333K4K...
..KK.K333K.KK...
.....K333K......
.....KKKKK......
`);

// #17 — Doomhorn the Minotaur  (curved horns + ring)
export const SP_BOSS_MINOTAUR = S(`
................
...K..KKKK..K...
..KK..KbbK..KK..
.KqK.KbeebK.KqK.
.KqK..KZZK..KqK.
.KqKKKenneKKKqK.
..KqebbbbbeqK...
..KqebbeebbeqK..
..KbbbbeebbbbK..
..KKbeeeebbKK...
...KbeeeeebK....
...KbeeeeebK....
...KKbeeebKK....
....Kb...bK.....
....KK...KK.....
................
`);

// #18 — The Nightmother  (purple matriarch, 8 legs)
export const SP_BOSS_NIGHTMOTHER = S(`
................
................
.K.....KK.....K.
..KK..KPPK..KK..
....KPPPPPPK....
...KPpUUUUpPK...
...KPpUKKKKpK...
...KKPpUUUUPK...
.K.KPpPPPPpPK.K.
..KKPpuuuupPKK..
..KPpuuuuuupK...
..KKPpPPPPpPKK..
.K.KKPPPPPPKK.K.
..KK........KK..
.K............K.
................
`);

// #19 — Warden of the Gate  (gilded armored knight)
export const SP_BOSS_WARDEN = S(`
................
......KKKK......
.....KWLLLWK....
....KWLZ22ZLK...
....KWLL22LLK...
....KWLLLLLLK...
....KWWWWWWWK...
...KKLLLLLLLLK..
..KWLLLLLLLLWK..
..KWLLYYYYLLWK..
..KWLLYWWYLLWK..
..KWLLLLLLLLWK..
..KKLLLLLLLLKK..
...KKLL..LLKK...
...KYK....KYK...
...KYK....KYK...
`);

// ============================================================
//  BOSSES — Act II (Designer Claude), floors 21-40
// ============================================================
export const SP_BOSS_VEXA = S(`
.......KK.......
......KIcIK.....
......KCccCK....
.....KCcZZcCK...
.....KCcZZcCK...
....KCcccccCK...
....KCccIIccK...
...KCCccIIccCK..
...KCKCccccCKK..
...KCKCccccCKK..
..KCKCKCccCKCK..
..KCK.KCccCK.K..
..KK.KCcccCK.K..
......KCccCK....
......KK..KK....
................
`);

export const SP_BOSS_KORRUN = S(`
................
....KK....KK....
....KCC..CCK....
...KCCccCCCK....
...KCcZIIZcK....
..KCcccCCcccK...
..KCcCCccCCcK...
..KCCccCCccCK...
..KCccccccccK...
.KCCCccCCccCCK..
.KCCcccCCcccCK..
.KCCcccccccCCK..
..KCKCccCCKCK...
..KK.KCcCK.KK...
.....KCcCK......
....KK....KK....
`);

export const SP_BOSS_YSHARA = S(`
....KK....KK....
...KuCK..KCuK...
....KCCuCCuC....
.....KCccCK.....
....KIZccZIK....
....KCcccccK....
...KuCccccCuK...
...KuCcZZcCuK...
..KuCCccccCCuK..
..KCCCccccCCCK..
..KCcccccccccK..
..KCcCKCCKCccK..
..KKCK.KK.KCKK..
....K..KK..K....
...KK..KK..KK...
................
`);

export const SP_BOSS_HELGRIM = S(`
.....KK.KK.KK...
....K1K1K1K1K...
....KOQqQqQOK...
...KKSSSSSSKK...
...KStSqSqStK...
..KStSqOOqStSK..
..KStttOOtttSK..
..KSStSqqSttSK..
..KSStSSSSttSK..
.KSStSSqqSStSK..
.KStSStttSStSK..
.KSttSStSStttK..
..KSSttSStSSKK..
....KStSStK.....
....KS....SK....
...KK......KK...
`);

export const SP_BOSS_OZMAEL = S(`
KK......KK....KK
K1K....K1K..K1K.
KQK...KQK..KQK..
.KQK.KQK..KQK...
.K1QqQ1KqQ1K....
.KQ1QqQ1QQK.....
.KqQqqQqqQK.....
.KqOOOOOOqK.....
.KqOORROOqK.....
.KqOOoooOOqK....
KqOOoooooOOqK...
KOOoooooooOOK...
KqOoOoOoOoOqK...
KKOoOoooooOKK...
.KK.KooooK.KK...
....K....K......
`);

export const SP_BOSS_DRUST = S(`
......KK..KK....
.....KIKIIKIK...
.....KIZIIZIK...
.....KIKIIKIK...
....KKIIIIIIKK..
...KIIIIIIIIIK..
...KIIIIIIIIIK..
...KIKIIIIKIIK..
...KIIIIIIIIIK..
...KIKIIIIKIIK..
....KKIIIIIIK...
.....KKIIIIKK...
....KIK.KKKIK...
....KIK..KKIK...
...KK......KK...
................
`);

export const SP_BOSS_SARN = S(`
.......KK.......
......KpPK......
......KuuK......
.....KPwwwPK....
....KPwxKxwPK...
....KPwzzzwPK...
....KPpwwwpPK...
....KPpuuupPK...
....KPuPPPuPK...
...KKPuPPPuPKK..
..KuPpuPPPupPuK.
..KuPpuPPPupPuK.
..KuKKPuPPPKKuK.
..KuK.KKPPK.KuK.
..KK..KK..KK.KK.
................
`);

export const SP_BOSS_BAIRGH = S(`
.......KK.......
......KuUK......
.....KKuPKK.....
.....KgGGGgK....
....KgGZZGgK....
....KGGgggGGK...
....KGgGGGgGK...
...KgGGHHGGgK...
...KgGHHHHGgK...
..KgGGHjjHGGgK..
..KgGGHjjHGGgK..
..KgGGGHHGGGgK..
...KKGGGGGKK....
.....KG.GK......
....KK...KK.....
................
`);

export const SP_BOSS_NYSSA = S(`
....KKK..KKK....
...KHHKuuKHHK...
...KHGuPuuGHK...
....KGZuuZGK....
....KGuPPuGK....
...KGGuuuuGGK...
..KGgGGuuGGgGK..
..KGGGuPuPuGGK..
..KGgGuPuuuGgK..
..KGGGGuuuGGGK..
..KGggGuuGgggK..
...KGgGGGGGgK...
....KKgGGgKK....
......KGGK......
.....KK..KK.....
................
`);

export const SP_BOSS_VERDANT = S(`
K.K..K.K..K.K..K
KHK.KHK..KHK..KH
.KKHKK.KKHKK.KKK
..KgGGGGGGGGGGK.
.KGGzzzzzzzzGGK.
.KGzKzzzzzzKzGK.
.KGzzKzzzzKzzGK.
.KGGzzzzzzzzGGK.
KGgGzGzKKzGzGgGK
KGGgGzzKKzzGgGGK
.KGGggGGGGggGGK.
..KGggHHHHggGK..
..KKgGGggGGgKK..
....KGggggGK....
....KGK..KGK....
....KK....KK....
`);

export const SP_BOSS_THROK = S(`
...KK......KK...
..KGGK....KGGK..
..KGgGK..KGgGK..
..KGZGK..KGZGK..
..KGggGKKGggGK..
..KGGGGooGGGGK..
...KGGOOOOGGK...
..KOOOOOOOOOOK..
..K4OOOOOOOO4K..
..K4OoooooOO4K..
..K4OoooooOO4K..
..KK4OOOOOO4KK..
....KOnnOOnnK...
....KK....KK....
....Kn....nK....
...KK......KK...
`);

export const SP_BOSS_VAELIN = S(`
.....KK..KK.....
....KLLKKLLK....
...KLW4444WLK...
...KLW4WW4WLK...
...KLW4WW4WLK...
...KLWWWWWWLK...
..KKLLWWWWLLKK..
..KLYWWLLWWYLK..
..KLYWLLLLWYLK..
..KLYWLLLLWYLK..
..KKLLWWWWLLKK..
...KKLWWWWLKK...
....KLWWWWLK....
....KK....KK....
....Kn....nK....
...KK......KK...
`);

export const SP_BOSS_MURA = S(`
K...K...K...K..K
.K..K...K...K.K.
.KupKK.KKuKK.KpK
..KpPuPuPuPuPK..
..KpPuZuuZuPK...
..KpPuPpppPuPK..
.KpPpuPPPPupPpK.
.KpPpuPPPPupPpK.
..KpPpupppPpK...
..KKPpPPPPpPKK..
.KpK.KPppPK.KpK.
.KK.KKKPPKKK.KK.
....K..KK..K....
...KK..KK..KK...
..KK....KK..KK..
................
`);

export const SP_BOSS_ISKVAR = S(`
.......K........
......KIK.......
.....KIZIK......
....KIIZIIK.....
....KIIIIIK.....
...KIIIZZIIK....
...KIICZZCIK....
...KICKZZKCIK...
...KICIZZICIK...
...KICCccCCIK...
...KKCCccCCKK...
....KCCccCCK....
.....KCccCK.....
....KCK..KCK....
....K......K....
...K........K...
`);

export const SP_BOSS_KHAAZUM = S(`
..KKKK..KKKK....
.KSSSSKKSSSSK...
.KSstStStsSSK...
.KSsLSStSLsSK...
.KSStSStSStSK...
.KSSttStttSSK...
KKKSSSStSSSSKKK.
KSSSLstStSLSSSK.
KSStSStSStSStSK.
KSStSStSStSStSK.
KKSSSSttSSSSSKK.
.KSSSStSSSSSK...
.KSStStStStSK...
.KK.KKttSK.KK...
....K....K......
...KK....KK.....
`);

export const SP_BOSS_MARROW = S(`
.......KK.......
......KLWLK.....
.....KLWLWLK....
....KKKLLLKK....
....KwzwwzwK....
...KwzKwwKzwK...
...KwzzwwzzwK...
...KKzzZZzzKK...
..KuPwzZZzwPuK..
..KuPpwwwwpPuK..
..KuPpwwwwpPuK..
..KuKpwwwwpKuK..
..KK.KpwwpK.KK..
.....KpwwpK.....
....KK....KK....
....KP....PK....
`);

export const SP_BOSS_VOLTHUS = S(`
....K....K......
...KIK..KIK.....
...KIZK.KIK.....
...KIZIKKIK.....
...KIZIIZIK.....
..KKCIIIZIKK....
.KCCCCCIIICCK...
.KCcCCCCCCCcK...
.KCcCCIICCCcK...
.KCcCCIICCCcK...
KCCcCCIICCCcCCK.
KCcCcCIICCcCcCK.
.KKCcCCIICCcKK..
...KKCCCCKK.....
...KIK..KIK.....
..KK......KK....
`);

export const SP_BOSS_EREVHAL = S(`
......KLLK......
.....KLWLWLK....
....KKKLLLKK....
...KrxRRRRxrK...
..KrRrxxxxrRrK..
..KrxRRrrRRxrK..
.KrRRrRRRRrRRrK.
.KrRRrxxxxrRRrK.
..KrRRrxxrRRrK..
...KKrRRRRrKK...
....KKrRRrKK....
....KrxRRxrK....
...KrRRRRRRrK...
...KKrRRRRrKK...
.....KrRRrK.....
......KrrK......
`);

export const SP_BOSS_HOLLOWCHOIR = S(`
..KKKK....KKKK..
.KwwwwK..KwwwwK.
KwzKKzwKKwzKKzwK
KwzKKzwwwwzKKzwK
KwzzzwwwwwwzzzwK
KKwzwwzwwzwwzwKK
.KKwwwzwwzwwwKK.
..KKKwwwwwwKKK..
.KKKwzKKKKzwKKK.
KwwwzKKKKKKzwwwK
KwzKKzwzwzKKzwwK
KwzKKzwzwzKKzwwK
KKwzzzwwwwzzzwKK
.KKwwwwwwwwwwKK.
..KKwwwwwwwwKK..
....KKKKKKKK....
`);

export const SP_BOSS_ZARAKHEL = S(`
.K1K.K1K..K1K.K1
K1KqK1KqK1K1KqK1
.KqQqKqQqKqQqKq.
KqQ1QqQ1QqQ1Q1Qq
.KqQRRRRRRRRQqK.
.KKQRr11111rRQKK
KQRr1qqLLqq1rRQK
KQR1qOLZZLOq1RQK
KQR1qOLZZLOq1RQK
KQRr1qqOOqq1rRQK
.KKQRr11111rRQKK
.KqQRRRRRRRRQqK.
KqQ1QqQ1QqQ1Q1Qq
.KqQqKqQqKqQqKq.
K1KqK1KqK1K1KqK1
.K1K.K1K..K1K.K1
`);
