import { S } from '../palette.js';

// ============================================================
//  PLAYER
// ============================================================
export const SP_PLAYER = S(`
................
......KKKK......
.....KCCCCK.....
....KCiiiiCK....
....KiZcciZK....
....KiCwwCiK....
....KCCwwCCK....
.....KCccCK.....
.....cCCCCc.....
....KCiiCCiK....
...KCiiCCiiCK...
...KCiCCCCCiK...
....KKCCCCKK....
.....KBBBBK.....
......K..K......
......K..K......
`);

// Class look: KNIGHT — plate armor, gold trim, glowing cyan visor.
export const SP_PLAYER_KNIGHT = S(`
................
......KKKK......
.....K4444K.....
....K455554K....
....K4iiii4K....
....K4LLLL4K....
....K455554K....
.....KW44WK.....
.K3WW444444WW3K.
..K44LWWWWL44K..
..K444LLLL444K..
...K44LLLL44K...
...K4LL44LL4K...
...K44K..K44K...
...K44K..K44K...
...K55K..K55K...
`);

// Class look: ROGUE — dark green hood, shadowed face, glowing eyes.
export const SP_PLAYER_ROGUE = S(`
................
......KKKK......
.....KGGGGK.....
....KGggggGK....
....KGkkkkGK....
....KiikkiiK....
....KkkeekkK....
.....KGGGGK.....
....KGGGGGGK....
...KGGggggGGK...
...KGGggggGGK...
...KbbWLLWbbK...
...KGGggggGGK...
...KggK..KggK...
...KkkK..KkkK...
...KBBK..KBBK...
`);

// ============================================================
//  COMMON MONSTERS — Act I
// ============================================================
export const SP_RAT = S(`
................
................
................
.........K..K...
.........Kbbk...
........KbBBbK..
.......KBBbZbK..
.......KBZBBnK..
......KKBnnBBK..
.....KbBBBBnBK..
....KBBnBnBBnK..
...KBBnBBBnBBK..
....KKBBBnBBKKK.
.....KKBBBKKBBK.
.......KKKKKBBK.
.........KKKKK..
`);

export const SP_GOBLIN = S(`
................
................
.....KKKKKK.....
....KGHHGGGK....
....KHGGHHGK....
....KHZGGZGK....
....KHHGGHHK....
.....KGGGGK.....
....KKnGGnKK....
...KnnGHHGnnK...
...KnGHjjHGnK...
...KnGHHHHGnK...
....KKHGGHKK....
.....KGG.KG.....
.....KG..KG.....
....KKK..KKK....
`);

export const SP_ARCHER = S(`
................
......KKKK......
.....KHHHHK.....
....KHGGGHK.....
....KHZjjZHK....
....KGjjjjGK....
....KGGGGGGK....
....KnGGGnKK....
....knGGGnK.....
.....nGGGnK.....
....KnHGGHnK....
.....nGHHGn..K..
.....nGHHGn..KK.
.....KG.GKK..K7K
.....KG..KG..K9.
....KKK..KKK.K9.
`);

export const SP_ORC = S(`
................
....KK....KK....
....KZK..KZK....
....KOZKKZOK....
...KOOOOOOOOK...
...KOOqqqqOOK...
...KOZqOOqZOK...
...KOOOOOOOOK...
...KKZOZZOZKK...
....KqOqqOqK....
....KOOqqOOK....
...KOOOqqOOOK...
...KOnnOOnnOK...
....KK....KK....
....Kn....nK....
...KK......KK...
`);

export const SP_TROLL = S(`
................
......KKKK......
.....KRRRRK.....
....KRrxxrRK....
....KrZxxZrK....
....KrxxxxrK....
....KRRrrRRK....
...KRRxxxxRRK...
..KRrxRRRRxrRK..
..KRxRRRRRRxRK..
..KRxRRrrRRxRK..
...KRRRrrRRRK...
....KRRRRRRK....
....KrR..RrK....
...KKR....RKK...
...KK......KK...
`);

export const SP_MAGE = S(`
................
.......PP.......
......PuPP......
.....KPPpPK.....
....KPPpPPPK....
....KPuZZuPK....
....KPPwwPPK....
.....KPpppPK....
....KPpPPpPK....
...KPpuuuupPK...
...KPpuuuupPK...
...KPpuPPupPK...
....KKpPPpKK....
.....Kp..pK.....
.....Kp..pK.....
....KKK..KKK....
`);

export const SP_MIMIC = S(`
................
................
....KKKKKKKK....
...KnBBBBBBnK...
...KBL77777BK...
...KKKKKKKKKK...
...KZxxZZxxZK...
...KKKKKKKKKK...
...KBxxxxxxBK...
...KnBnBBnBnK...
...K77B77B77K...
....KKKKKKKK....
......KKKK......
......K..K......
......K..K......
......KKKK......
`);

// ============================================================
//  CHEST + MERCHANT
// ============================================================
export const SP_CHEST = S(`
................
................
....KKKKKKKK....
...K77777777K...
...K7LLLLLL7K...
...K7L7777L7K...
...K7L7LL7L7K...
...K7L7LL7L7K...
...K7LLLLLL7K...
...KKKKKKKKKK...
...K77777777K...
...K7n7L7n77K...
...K77777777K...
...KKKKKKKKKK...
................
................
`);

export const SP_MERCHANT = S(`
................
......KKKK......
.....KLLLLK.....
....KLeeeeLK....
....KLZeeZLK....
....KLebbeLK....
....KLLLLLLK....
....KYWWWWYK....
...KYWLLLLWYK...
...KYWLnnLWYK...
...KYWLnnLWYK...
...KYWLLLLWYK...
....KYWWWWYK....
.....KK..KK.....
.....KY..YK.....
....KKK..KKK....
`);

// ============================================================
//  ACT II COMMONS — v2 revamped sprites
// ============================================================
export const SP_PLAYER_V2 = S(`
................
......KLLK......
.....KKLLKK.....
....KCiiiiCK....
....KiZcciZK....
....KiCwwCiK....
....KCCwwCCK....
....K3CccC3K....
...K34CCCC43K...
...K3CiLLiC3K...
...K3CiLLiC3K...
....KCCCCCCK....
....KKCCCCKK....
....K4CBBC4K....
.....KBKKBK.....
.....KK..KK.....
`);

export const SP_RAT_V2 = S(`
................
................
................
.........KK.....
........KBbk....
........KbBbK...
.......KBBbnbK..
.......KBZBxnK..
......KKBnnxBK..
.....KbBBBnBnK..
....KBBnBnBBnK..
...KBBnBBBnBBK..
....KKBBBnBBKKK.
.....KKBBBKKnBK.
.......KKKKKnBK.
.........KKKKK..
`);

export const SP_GOBLIN_V2 = S(`
................
................
.....KKKKKK.....
....KGHHGGGK....
....KHGRGHRK....
....KHZGGZGK....
....KHHrGHHK....
.....KGGGGK.....
....KKBGGBKK....
...KBGGHHGGBK...
...KnGHjjHGnK...
...KnGHHHHGnK...
....KKHGGHKK....
.....KGn.nG.....
.....KG..KG.....
....KKK..KKK....
`);

export const SP_ARCHER_V2 = S(`
................
......KKKK......
.....KgGGgK.....
....KgGHHGgK....
....KgZjjZgK....
....KGjjjjGK....
....KGgggGGK....
....KnGGGnKK....
....knGGGnK.K...
.....nGGGn..KK..
....KnHGGHnKK7K.
.....nGHHGnK7K..
.....nGHHGnK7K..
.....KG.GKKK7K..
.....KG..KGK7K..
....KKK..KKKKK..
`);

export const SP_ORC_V2 = S(`
................
....KK....KK....
....KZK..KZK....
....KOZKKZOK....
...KOOOOOOOOK...
...KOOqqqqOOK...
...KOZqRRqZOK...
...KOOOORRROK...
...KKZOZZOZKK...
....KqOqRqOqK...
....KOOqqOOqK...
...KOOOqqOOOK...
...KOnnOOnnOK...
....KK....KK....
....Kn....nK....
...KK......KK...
`);

export const SP_TROLL_V2 = S(`
................
......KKKK......
.....KRGRRK.....
....KRrxxrRK....
....KrZxxZrK....
....KrxxxxrK....
....KRRrrRRK....
...KRRxxxxRRK...
..KRrxRGRRxrRK..
..KRxRGGRGRxRK..
..KRxRRrrRRxRK..
...KRRRrrGRRK...
....KRRRRRRK....
....KrR..RrK....
...KKR....RKK...
..KK........KK..
`);

export const SP_MAGE_V2 = S(`
.......KK.......
......KuLK......
......KLLK......
.....KPPpPK.....
....KPPpPPPK....
....KPLZZLPK....
....KPPwwPPK....
.....KPpppPK....
....KPpPPpPK....
...KPpuuuupPK...
...KPpuLLuupK...
...KPpuPPupPK...
....KKpPPpKK....
.....Kp..pK.....
.....Kp..pK.....
....KKK..KKK....
`);

export const SP_MIMIC_V2 = S(`
................
................
....KKKKKKKK....
...KnBBBBBBnK...
...KBL7L7L7BK...
...KKKKKKKKKK...
...KZxxZZxxZK...
...KKxKKKKxKK...
...KBxxxxxxBK...
...KnBnBBnBnK...
...K7LB7LB7LK...
....KKKKKKKK....
......KKKK......
......K..K......
....KKKKKKKK....
......KKKK......
`);

// ============================================================
//  ACT II NEW COMMONS
// ============================================================
export const SP_WRAITH = S(`
................
.......KK.......
......KIIK......
.....KIZIIK.....
....KIKIIKIK....
....KIIKKIIK....
....KIIIIIIK....
....KIIIiIIK....
.....KIIIIK.....
.....KIIIIK.....
....KIIiIIIK....
....KIiIIIiK....
....KIIiIIIK....
.....KIIIIK.....
......KKKK......
................
`);

export const SP_HOUND = S(`
................
................
.......KKKK.....
......KnnnnK....
.....KnxKxnnK...
.....KnnnnnnK...
....KKnnnnnnKK..
...KnBnnnnnnnK..
...KnBnnnBBnnK..
...KKnnnnnnnKK..
....KnBnnBnK....
....KnBnnBnK....
....KnnnnnnK....
....KK....KK....
....Kn....nK....
...KK......KK...
`);

export const SP_SPITTER = S(`
................
................
.....KKKKKK.....
....KGGggGGK....
...KGHGGGGHGK...
...KGHKHHKHGK...
...KGHHHHHHGK...
....KGjjjjGK....
...KKGHHHHGKK...
..KGGHHHHHHGGK..
..KGGgGGGGgGGK..
..KGGgGGGGgGGK..
...KKGGggGGKK...
....KGK..KGK....
....KK....KK....
................
`);

export const SP_GLASSHUSK = S(`
................
......KK.K......
......KIIKK.....
.....KIZIIK.....
.....KIKIIK.....
.....KIIIIK.....
....KKIIIIKK....
...KIIIIIIIIK...
...KIIIIIIIIK...
....KIIIIIIK....
....KIKIIKIK....
....KIKIIKIK....
....KKIIIIKK....
.....KK..KK.....
.....KI..IK.....
....KK....KK....
`);

export const SP_CINDERLING = S(`
................
.......K........
......K1K.......
.....K11qK......
.....K1qKK......
....KqQqqKK.....
....KqQQQqK.....
....KqQ1QqK.....
....KqQOOQqK....
...KqQOoOOQqK...
...KqQOoOoOqK...
....KQQooQqK....
....KqQOOQqK....
....KK.qq.KK....
....Ko....oK....
...KK......KK...
`);

export const SP_BRINE = S(`
................
................
......KKKK......
.....KCccCK.....
....KCcZIZCK....
....KCccccCK....
....KcCCCCcK....
...KcCccccCcK...
...KcCccccCcK...
....KCccccCK....
...KCKCccCKCK...
..KCKKKCCKKKCK..
..KCK..KK..KCK..
..KK........KK..
................
................
`);

export const SP_BONEKNIGHT = S(`
................
....KK....KK....
....K44KK44K....
....K4z44z4K....
...K4zRKKRz4K...
...K4zzKKzz4K...
...K44zzzz44K...
....K442244K....
...K34433443K...
...K3z3443z3K...
...K3zz4434z3K..
...K344444443K..
....K33443K3K...
....KK4334KK....
....K4....4K....
...KK......KK...
`);
