"use strict";
/* ============================================================
   Caves of Qlud — sprite + palette module
   PAL is the game's palette. Item sprites + the detailed hero
   are authored in that palette (16x16, hero is 16x24).
   Rows are auto-padded so the grid is always rectangular.
   ============================================================ */

const PAL = {
  '.': null,
  'K': '#070509', 'k': '#1a1410',
  's': '#1f1c18', 'S': '#3c352e', 't': '#5a5048', 'T': '#7a6f60',
  'd': '#1c1208', 'n': '#3a2618', 'B': '#704a26', 'b': '#a8784a', 'e': '#d4a878',
  '6': '#4a2e18', '7': '#8a5a2e',
  'g': '#1a3010', 'G': '#3a6b22', 'H': '#7bc96f', 'j': '#b4e090',
  'o': '#5a2810', 'O': '#a04818', 'q': '#d97a3a', 'Q': '#f4a85a',
  'r': '#4a0e0a', 'R': '#a0302a', 'x': '#e0524a', 'X': '#ff8a7a',
  'y': '#3a2410', 'Y': '#8a6020', 'W': '#e8b75c', 'L': '#ffd866', '9': '#fff0c0',
  'c': '#1a3a52', 'C': '#3a7a9a', 'i': '#6fd3ff', 'I': '#a8e8ff',
  'p': '#1c0e2c', 'P': '#5a2a7a', 'u': '#c77dff', 'U': '#e8c0ff',
  '2': '#1c2230', '3': '#525e6e', '4': '#9aa6b4', '5': '#d4dce6',
  'w': '#e9e0cf', 'Z': '#ffffff', 'z': '#d6c6a8', '1': '#ff5a3a',
};

function S(art){
  const arr = art.replace(/^\n/, '').replace(/\s+$/, '').split('\n').map(s => s.replace(/^\s+/, ''));
  let w = 0; for(const r of arr) w = Math.max(w, r.length);
  return arr.map(r => r.padEnd(w, '.'));
}

/* ============================================================
   HERO — detailed warrior, greatsword planted (16 x 24)
   horned helm · glowing cyan visor · pauldrons · cape · greaves
   ============================================================ */
const SP_HERO = S(`
...KL......LK...
...K4......4K...
...K4KK..KK4K...
....KK4444KK....
...K44555544K...
...KL455554LK...
...K45iiii54K...
...K45333354K...
....K433334K....
..KL44K22K44LK..
..K444K33K444K..
.RK444K3II3K444KR
.RK44KLWWWWLK44KR
.RKnnK222222KnnKR
.RK2233553322K.R
.RK2233553322K.R
.RK22LWWWWL22K.R
...K23355332K...
...K23355332K...
...K22K55K22K...
...K22K55K22K...
...K33K55K33K...
..KK44KIIK44KK..
...KK......KK...
`);

/* ============================================================
   WEAPONS (16 x 16)
   ============================================================ */
const SP_DAGGER = S(`
................
.........KK.....
........K5K.....
.......K54K.....
......K54K......
.....K54K.......
....K54K........
...K554K........
..KW44WK........
.KWWWWWWK.......
...KnnK.........
...KnnK.........
...K77K.........
...KKKK.........
................
................
`);

const SP_SWORD = S(`
................
.......KK.......
......K5K.......
......K54K......
......K54K......
......K54K......
......K54K......
......K54K......
......K54K......
....KWWWWWK.....
......KnK.......
......KnK.......
......K7K.......
......KKK.......
................
................
`);

const SP_AXE = S(`
................
......KKKK......
......K33KK.....
......K3334K....
......K33334K...
......K333334K..
......K33334K...
......K3334K....
......KnKKK.....
......KnK.......
......KnK.......
......KnK.......
......KnK.......
......K7K.......
......KKK.......
................
`);

const SP_HAMMER = S(`
................
....KKKKKKK.....
...K3334555K....
...K3334555K....
...K3334555K....
...KKKKKKKKK....
......KnK.......
......KnK.......
......KnK.......
......KnK.......
......KnK.......
......KnK.......
......K7K.......
......KKK.......
................
................
`);

const SP_BLADE_FIRE = S(`
................
.......KK.......
......KLK.......
......KxLK......
......KxRK......
......KxRK......
......KxRK......
......KxRK......
......KxRK......
....KLLWLLK.....
......KrK.......
......KrK.......
......KLK.......
......KKK.......
................
................
`);

const SP_BLADE_FROST = S(`
................
.......KK.......
......KIK.......
......KiIK......
......KiCK......
......KiCK......
......KiCK......
......KiCK......
......KiCK......
....KIIiIIK.....
......KcK.......
......KcK.......
......KIK.......
......KKK.......
................
................
`);

/* ============================================================
   ARMOR — torso (16 x 16)
   ============================================================ */
const SP_ARM_LEATHER = S(`
................
...KK....KK.....
..KbBnnnnBbK....
.KbBnnnnnnBbK...
.KbnBBBBBBnbK...
.KbnB7nn7BnbK...
.KbnBnnnnBnbK...
.KbnBnnnnBnbK...
.KbnBBBBBBnbK...
.KbBnnnnnnBbK...
..KbBnnnnBbK....
..KbnnnnnnbK....
...KbnnnnbK.....
....KbnnbK......
.....KKKK.......
................
`);

const SP_ARM_CHAIN = S(`
................
...KK....KK.....
..K33tttt33K....
.K3t3t3t3t3K....
.K33t3t3t33K....
.K3t3t3t3t3K....
.K33t3t3t33K....
.K3t3t3t3t3K....
.K33t3t3t33K....
.K3t3t3t3t3K....
..K33tttt33K....
..K3t3t3t3K.....
...K33tt33K.....
....K3tt3K......
.....KKKK.......
................
`);

const SP_ARM_PLATE = S(`
................
...KK....KK.....
..K45KKKK54K....
.K4554444554K...
.K45544445 54K..
.K4554334554K...
.K4544334454K...
.K4554334554K...
.K45544445 54K..
.K4554444554K...
..K455444554K...
..K45444454K....
...K4554554K....
....K45554K.....
.....KKKK.......
................
`);

/* ============================================================
   HELMETS (16 x 16)
   ============================================================ */
const SP_HELM_CAP = S(`
................
................
.....KKKK.......
....KbBBbK......
...KbBnnBbK.....
..KbBnnnnBbK....
..KbnnnnnnbK....
..KbnnnnnnbK....
..KbBnnnnBbK....
...KbBBBBbK.....
....KbKKbK......
................
................
................
................
................
`);

const SP_HELM_IRON = S(`
................
................
....KKKKKK......
...K455554K.....
..K45555554K....
..K455KK554K....
..K4555K554K....
..K4555K554K....
..K45555554K....
...K455554K.....
....KK..KK......
................
................
................
................
................
`);

const SP_HELM_GREAT = S(`
................
................
....KKKKKK......
...K455554K.....
..K45555554K....
.K4555555554K...
.K4LLLLLLLL4K...
.K45KKKKKK54K...
.K4555555554K...
.K4555555554K...
.K45555 5554K...
.K45555554K....
..K455554K.....
...KK..KK......
................
................
`);

/* ============================================================
   SHIELDS (16 x 16)
   ============================================================ */
const SP_SHD_WOOD = S(`
................
.....KKKK.......
...KK7777KK.....
..K7BnnnnB7K....
.K7BnbbbbnB7K...
.K7nbB77Bbn7K...
.K7nb7nn7bn7K...
.K7nb7nn7bn7K...
.K7nbB77Bbn7K...
.K7BnbbbbnB7K...
..K7BnnnnB7K....
...KK7777KK.....
.....KKKK.......
................
................
................
`);

const SP_SHD_KITE = S(`
................
...KKKKKK.......
..K433334K.....
..K43LL34K.....
..K4L33L4K.....
..K43LL34K.....
..K433334K.....
..K43LL34K.....
...K4334K......
...K4334K......
....K33K.......
....K33K.......
.....KK........
................
................
................
`);

const SP_SHD_TOWER = S(`
................
..KKKKKKKK.....
..K455554K.....
..K4LLLL4K.....
..K455554K.....
..K45KK54K.....
..K455554K.....
..K4LLLL4K.....
..K455554K.....
..K45KK54K.....
..K455554K.....
..K4LLLL4K.....
..K455554K.....
..KKKKKKKK.....
................
................
`);

const SP_SHD_LEGEND = S(`
................
....KKKKKK......
..KKLWWWWLKK....
.KLWYYYYYYWLK...
.KLWYxRRxYWLK...
.KLWYRxxRYWLK...
.KLWYxRRxYWLK...
.KLWYYYYYYWLK...
..KLWYYYYWLK....
..KLWYYYYWLK....
...KLWYYWLK.....
....KLWWLK......
.....KLLK.......
......KK........
................
................
`);

/* ============================================================
   BOOTS (16 x 16)
   ============================================================ */
const SP_BOOTS_LEATHER = S(`
................
................
..KbBK...KbBK...
..KbBK...KbBK...
..KbBK...KbBK...
..KbBK...KbBK...
..KbBK...KbBK...
..KbBK...KbBK...
..KnnK...KnnK...
..KbBK...KbBK...
..KbBK...KbBK...
.KbBBbK.KbBBbK..
.KbBBbK.KbBBbK..
.KeBBeK.KeBBeK..
.KKKKKK.KKKKKK..
................
`);

const SP_BOOTS_IRON = S(`
................
................
..K44K...K44K...
..K45K...K45K...
..K45K...K45K...
..K45K...K45K...
..K45K...K45K...
..K33K...K33K...
..K45K...K45K...
..K45K...K45K...
.K4554K.K4554K..
.K4554K.K4554K..
.K5LL5K.K5LL5K..
.KKKKKK.KKKKKK..
................
................
`);

/* ============================================================
   CHARMS — purple gem, colored core (16 x 16)
   ============================================================ */
function charmGem(core){
  return S(`
................
......KKKK......
.....KuUUuK.....
....KuU&&UuK....
...KuU&&&&UuK...
...KuU&&&&UuK...
...KuU&&&&UuK...
...KuU&&&&UuK...
....KuU&&UuK....
.....KuUUuK.....
......KuuK......
.......KK.......
................
................
................
................
`.replace(/&/g, core));
}
const SP_CHARM_VIGOR  = charmGem('x'); // red
const SP_CHARM_EMBER  = charmGem('Q'); // orange
const SP_CHARM_SAVAGE = charmGem('Z'); // white
const SP_CHARM_GUARD  = charmGem('4'); // steel
const SP_CHARM_FOCUS  = charmGem('i'); // cyan

/* ============================================================
   CONSUMABLES / MISC (16 x 16)
   ============================================================ */
const SP_POTION = S(`
................
................
......KKKK......
......K..K......
......K33K......
......K33K......
.....KKuuKK.....
....KuuUUuuK....
....KuuuuuuK....
....KupuuupK....
....KupuuupK....
....KKuuuuKK....
.....KKuuKK.....
......KKKK......
................
................
`);

const SP_GOLD = S(`
................
................
................
......KKKK......
.....KLLWLK.....
....KLLWWWLK....
....KLWWLLWLK...
....KLWLLWWLK...
....KLWWLLWLK...
....KLLWWWLLK...
.....KKLLLLK....
......KKKKK.....
......K..LK.....
.....KLLLLLK....
......KKKKKK....
................
`);

const SP_ARROW = S(`
................
................
................
................
........KK......
.......KbK......
....KKKbBK......
...KbBBBK.......
..KbBBBK........
...KbBBBK.......
....KKKbBK......
.......KbK......
........KK......
................
................
................
`);

/* ============================================================
   STATUS ICONS (16 x 16)
   ============================================================ */
const SP_REGEN = S(`
................
................
.......KK.......
......KGHK......
......KHHK......
....KKHHHHKK....
...KHHHHHHHHK...
...KHHHGGHHHK...
...KHHHGGHHHK...
....KHHHHHHK....
.....KHHHHK.....
......KHHK......
.......KK.......
................
................
................
`);

const SPRITES = {
  hero: SP_HERO,
  // weapons
  wpn_dagger: SP_DAGGER, wpn_sword: SP_SWORD, wpn_axe: SP_AXE, wpn_hammer: SP_HAMMER,
  wpn_fire: SP_BLADE_FIRE, wpn_frost: SP_BLADE_FROST,
  // armor
  arm_leather: SP_ARM_LEATHER, arm_chain: SP_ARM_CHAIN, arm_plate: SP_ARM_PLATE,
  // helmets
  helm_cap: SP_HELM_CAP, helm_iron: SP_HELM_IRON, helm_great: SP_HELM_GREAT,
  // shields
  shd_wood: SP_SHD_WOOD, shd_kite: SP_SHD_KITE, shd_tower: SP_SHD_TOWER, shd_legend: SP_SHD_LEGEND,
  // boots
  boots_leather: SP_BOOTS_LEATHER, boots_iron: SP_BOOTS_IRON,
  // charms
  charm_vigor: SP_CHARM_VIGOR, charm_ember: SP_CHARM_EMBER, charm_savage: SP_CHARM_SAVAGE,
  charm_guard: SP_CHARM_GUARD, charm_focus: SP_CHARM_FOCUS,
  // misc
  potion: SP_POTION, gold: SP_GOLD, arrow: SP_ARROW, regen: SP_REGEN,
};

/* ---------------- renderer ---------------- */
function drawSprite(canvas, name, scale){
  const lines = SPRITES[name];
  if(!lines){ return; }
  const H = lines.length, W = lines[0].length;
  const dpr = Math.max(1, window.devicePixelRatio || 1);
  const px = scale * dpr;
  canvas.width = W * px;
  canvas.height = H * px;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  for(let y = 0; y < H; y++){
    const row = lines[y];
    for(let x = 0; x < W; x++){
      const c = PAL[row[x]];
      if(c){ ctx.fillStyle = c; ctx.fillRect(x * px, y * px, px, px); }
    }
  }
}

function paintAllSprites(){
  document.querySelectorAll('canvas[data-spr]').forEach(cv => {
    const name = cv.getAttribute('data-spr');
    const scale = parseInt(cv.getAttribute('data-scale') || '4', 10);
    drawSprite(cv, name, scale);
  });
}

/* ---------------- stage scaler (fixed 16:9, desktop only) ---------------- */
function fitStage(stageSel, baseW, baseH){
  const stage = document.querySelector(stageSel);
  if(!stage) return;
  const apply = () => {
    if(window.matchMedia('(max-width:860px)').matches){ stage.style.transform = 'none'; return; }
    const s = Math.min(window.innerWidth / baseW, window.innerHeight / baseH);
    stage.style.transform = `translate(-50%, -50%) scale(${s})`;
  };
  apply();
  window.addEventListener('resize', apply);
}

/* ============================================================
   LAYERED PAPER-DOLL  (16 x 24, all layers share this grid)
   base body + per-slot overlays that composite in z-order:
   base -> boots -> armor -> weapon -> shield -> helmet
   ============================================================ */
const PD_BASE = S(`
..................
......KKKKKK......
.....KnnnnnnK.....
.....KeeeeeeK.....
.....KeecceeK.....
.....KeebbeeK.....
......KbbbbK......
.......KbbK.......
...KSSSSSSSSSSK...
...KSttttttttSK...
...KStttWWtttSK...
...KSttttttttSK...
...KSttttttttSK...
...KeetttttteeK...
...KbettttttebK...
....KWWWLLWWWK....
....K22K..K22K....
....K22K..K22K....
....K23K..K32K....
....K23K..K32K....
....K22K..K22K....
....KbbK..KbbK....
...KbbbK..KbbbK...
...KKKKK..KKKKK...
`);

/* class-specific hero bodies (same 18x24 grid as PD_BASE so the equipment
   layers line up). KNIGHT: steel plating + cyan visor. ROGUE: dark green
   hood + shadowed face. Equipment still layers on top of these. */
const PD_BASE_KNIGHT = S(`
..................
......KKKKKK......
.....K444444K.....
.....KeeeeeeK.....
.....KeeiieeK.....
.....KeebbeeK.....
......KbbbbK......
.......KbbK.......
...K3333333333K...
...K3444444443K...
...K3444LL4443K...
...K3444444443K...
...K3444444443K...
...Kee444444eeK...
...Kbe444444ebK...
....KWWWLLWWWK....
....K22K..K22K....
....K22K..K22K....
....K23K..K32K....
....K23K..K32K....
....K22K..K22K....
....KbbK..KbbK....
...KbbbK..KbbbK...
...KKKKK..KKKKK...
`);
const PD_BASE_ROGUE = S(`
..................
......KKKKKK......
.....KGGGGGGK.....
.....KeeeeeeK.....
.....KeeHHeeK.....
.....KeebbeeK.....
......KbbbbK......
.......KbbK.......
...KGGGGGGGGGGK...
...KGggggggggGK...
...KGgggWWgggGK...
...KGggggggggGK...
...KGggggggggGK...
...KeeggggggeeK...
...KbeggggggebK...
....KWWWLLWWWK....
....K22K..K22K....
....K22K..K22K....
....K23K..K32K....
....K23K..K32K....
....K22K..K22K....
....KbbK..KbbK....
...KbbbK..KbbbK...
...KKKKK..KKKKK...
`);

/* ============================================================
   PAPER-DOLL OVERLAYS — all authored as full-height (16x24)
   grids registered to PD_BASE so each piece lands on the right
   body part instead of stacking at the top-left:
     head  = rows 1-7   (cols 4-9)
     torso = rows 7-14  (cols 4-9, pauldrons to 2/11)
     feet  = rows 19-23 (legs at cols 5 & 8)
     weapon= LEFT margin  (cols 0-3)  — held beside the hero
     shield= RIGHT margin (cols 10-14) — strapped beside the hero
   This keeps every item clear of the others when equipped.
   ============================================================ */

/* ---- helmets (sit on the head, rows 1-7) ---- */
const PD_HELM_GREAT = S(`
..................
......KKKKKK......
.....K444444K.....
.....K4LLLL4K.....
.....KKiiiiKK.....
.....K444444K.....
......K4444K......
.......K44K.......
`);
const PD_HELM_IRON = S(`
..................
......KKKKKK......
.....K444444K.....
.....K455554K.....
.....K4K..K4K.....
`);
const PD_HELM_CAP = S(`
..................
......KKKKKK......
.....KbBBBBbK.....
.....KKKKKKKK.....
`);

/* ---- armor (sits on the torso, rows 8-15) ---- */
const PD_ARM_PLATE = S(`
..................
..................
..................
..................
..................
..................
..................
..................
...K4444444444K...
...K4WWWWWWWW4K...
...K4W444444W4K...
...K4444444444K...
...K4444444444K...
...Ke44444444eK...
...Kb44444444bK...
....K44444444K....
`);
const PD_ARM_CHAIN = S(`
..................
..................
..................
..................
..................
..................
..................
..................
...K3333333333K...
...Kt3t3t3t3t3K...
...K3t3t3t3t3tK...
...Kt3t3t3t3t3K...
...K3t3t3t3t3tK...
...Ke3t3t3t3teK...
...KbttttttttbK...
....K33333333K....
`);
const PD_ARM_LEATHER = S(`
..................
..................
..................
..................
..................
..................
..................
..................
...KBBBBBBBBBBK...
...KBnnnnnnnnBK...
...KBn7nnnn7nBK...
...KBnnnnnnnnBK...
...KBnnnnnnnnBK...
...KennnnnnnneK...
...KbnnnnnnnnbK...
....KBBBBBBBBK....
`);

/* ---- weapons (gripped in the right fist, rising up the left side) ---- */
const PD_WPN_SWORD = S(`
..................
..................
...5..............
..54..............
..54..............
..54..............
..54..............
..54..............
..54..............
..54..............
..54..............
..54..............
.WWWW.............
..nn..............
..nn..............
.WLLW.............
`);
const PD_WPN_FIRE = S(`
..................
..................
...L..............
..x1..............
..x1..............
..xQ..............
..x1..............
..x1..............
..xQ..............
..x1..............
..x1..............
..x1..............
.LWWL.............
..nn..............
..nn..............
.LWWL.............
`);
const PD_WPN_FROST = S(`
..................
..................
...I..............
..iI..............
..iI..............
..iC..............
..iI..............
..iI..............
..iC..............
..iI..............
..iI..............
..iI..............
.CIIC.............
..cc..............
..cc..............
.CIIC.............
`);
const PD_WPN_AXE = S(`
..................
....nn............
....nn............
KK44nn............
K344nn............
K344nn............
KK4Knn............
....nn............
....nn............
....nn............
....nn............
....nn............
....nn............
....nn............
....77............
`);
const PD_WPN_HAMMER = S(`
..................
KKKKnn............
K35Knn............
K35Knn............
KKKKnn............
....nn............
....nn............
....nn............
....nn............
....nn............
....nn............
....nn............
....nn............
....nn............
....77............
`);
const PD_WPN_DAGGER = S(`
..................
..................
..................
..................
..................
..................
...5..............
..54..............
..54..............
..54..............
..54..............
..54..............
.WWWW.............
..nn..............
..nn..............
`);

/* ---- shields (strapped on the left arm, right side) ---- */
const PD_SHD_LEGEND = S(`
..................
..................
..................
..................
..................
..................
............KKKKKK
............KWWWWK
............KWxxWK
............KYxxYK
............KYxxYK
............KWxxWK
............KWWWWK
.............KWWK.
..............KK..
`);
const PD_SHD_KITE = S(`
..................
..................
..................
..................
..................
..................
............KKKKKK
............K4444K
............K4LL4K
............K4444K
............K4LL4K
.............K44K.
.............K44K.
..............KK..
`);
const PD_SHD_WOOD = S(`
..................
..................
..................
..................
..................
..................
.............KKKK.
............K7BB7K
............KBnnBK
............KBnnBK
............K7BB7K
.............KKKK.
`);
const PD_SHD_TOWER = S(`
..................
..................
..................
..................
..................
..................
............KKKKKK
............K4LL4K
............K4444K
............K4LL4K
............K4444K
............K4LL4K
............K4444K
............KKKKKK
`);

/* ---- boots (over the legs/feet, rows 19-23) ---- */
const PD_BOOTS_LEATHER = S(`
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
....K66K..K66K....
....K6BK..KB6K....
....KBBK..KBBK....
...KBBBK..KBBBK...
...KKKKK..KKKKK...
`);
const PD_BOOTS_IRON = S(`
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
..................
....K44K..K44K....
....K45K..K54K....
....K55K..K55K....
...K455K..K554K...
...KKKKK..KKKKK...
`);

Object.assign(SPRITES, {
  pd_base: PD_BASE, pd_base_knight: PD_BASE_KNIGHT, pd_base_rogue: PD_BASE_ROGUE,
  pd_helm_great: PD_HELM_GREAT, pd_helm_iron: PD_HELM_IRON, pd_helm_cap: PD_HELM_CAP,
  pd_arm_plate: PD_ARM_PLATE, pd_arm_chain: PD_ARM_CHAIN, pd_arm_leather: PD_ARM_LEATHER,
  pd_wpn_fire: PD_WPN_FIRE, pd_wpn_frost: PD_WPN_FROST, pd_wpn_sword: PD_WPN_SWORD,
  pd_wpn_axe: PD_WPN_AXE, pd_wpn_hammer: PD_WPN_HAMMER, pd_wpn_dagger: PD_WPN_DAGGER,
  pd_shd_legend: PD_SHD_LEGEND, pd_shd_kite: PD_SHD_KITE, pd_shd_wood: PD_SHD_WOOD, pd_shd_tower: PD_SHD_TOWER,
  pd_boots_leather: PD_BOOTS_LEATHER, pd_boots_iron: PD_BOOTS_IRON,
});

const HERO_ORDER = ['boots', 'armor', 'weapon', 'shield', 'helmet'];
// eq: { boots, armor, weapon, shield, helmet } -> layer key or null/undefined
function drawLayeredHero(canvas, eq, scale, baseKey){
  const base = (baseKey && SPRITES[baseKey]) || SPRITES.pd_base;
  const H = base.length, W = base[0].length;
  const dpr = Math.max(1, window.devicePixelRatio || 1);
  const px = scale * dpr;
  canvas.width = W * px;
  canvas.height = H * px;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  const stack = [base];
  for(const slot of HERO_ORDER){
    const key = eq && eq[slot];
    if(key && SPRITES[key]) stack.push(SPRITES[key]);
  }
  for(const lines of stack){
    for(let y = 0; y < lines.length; y++){
      const row = lines[y];
      for(let x = 0; x < row.length; x++){
        const c = PAL[row[x]];
        if(c){ ctx.fillStyle = c; ctx.fillRect(x * px, y * px, px, px); }
      }
    }
  }
}

window.QLUD = { PAL, SPRITES, drawSprite, drawLayeredHero, paintAllSprites, fitStage };
